# Generated by Django 5.2.7 on 2025-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="equipment",
            name="item_number",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipment",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_photos/"
            ),
        ),
    ]
