# Generated by Django 5.2.7 on 2025-10-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "requests",
            "0002_remove_equipment_serial_number_equipment_item_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("New Equipment Request", "New Equipment Request"),
                            ("Replacement Request", "Replacement Request"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
