# Generated by Django 5.2.7 on 2025-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0003_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="business_case",
            field=models.TextField(default="Not provided"),
        ),
        migrations.AddField(
            model_name="request",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="type",
            field=models.CharField(default="Not Provided", max_length=100),
            preserve_default=False,
        ),
    ]
